module.exports  = {
    htmlDir:[
        {
            index:'index',
            title:'es6-normal'
        },
        {
            index:'destructuring',
            title:'解构赋值'
        },
        {
            index:'aboutString',
            title:'字符串扩展'
        },
        {
            index:'aboutRegExp',
            title:'正则扩展'
        },
    ]
}
