module.exports  = {
    htmlDir:[
        {
            index:'index',
            title:'es6-normal'
        },
        {
            index:'destructuring',
            title:'解构赋值'
        },
        {
            index:'aboutString',
            title:'字符串扩展'
        },
        {
            index:'aboutRegExp',
            title:'正则扩展'
        },
        {
            index:'aboutNumber',
            title:'数值扩展'
        },
        {
            index:'aboutFunction',
            title:'函数扩展'
        },
        {
            index:'aboutArray',
            title:'数组扩展'
        },
        {
            index:'aboutObject',
            title:'对象扩展'
        },
        {
            index:'aboutObjectNewMethods',
            title:'对象的新增方法'
        },
        {
            index:'aboutSymbol',
            title:'Symbol'
        },
        {
            index:'aboutSetAndMap',
            title:'Set和Map'
        },
        {
            index:'aboutProxy',
            title:'关于Proxy'
        },
        {
            index:'aboutReflect',
            title:'关于Reflect'
        },
        {
            index:'aboutPromise',
            title:'关于Promise'
        },
        {
            index:'aboutIterator',
            title:'关于Iterator'
        },
        {
            index:'aboutGenerator',
            title:'关于Generator'
        },
        {
            index:'aboutGeneratorAsync',
            title:'关于Generator异步用法'
        },
        {
            index:'aboutAsync',
            title:'关于Async'
        },
        {
            index:'aboutClass',
            title:'关于Class'
        },
        {
            index:'aboutClassInherit',
            title:'关于Class继承'
        },
    ]
};
